/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.1 got.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/got-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Body_1_DefaultMaterial~1_0001'].geometry} material={materials.DefaultMaterial1} position={[-0.29, 0, 0.19]} />
    </group>
  )
}

useGLTF.preload('/got-transformed.glb')
